---
- name: Utilities | Load the distribution specific variables
  include_vars: "{{ansible_os_family}}.yml"

- name: Utilities | Make sure some basic utilities are installed
  apt:
    pkg: "{{utilities_base}}"

- name: Utilities | Make sure some Debian specific utilities are installed
  apt:
    pkg: "{{utilities_distribution_debian}}"
  when: ansible_os_family == "Debian"

- name: Utilities | Make sure some Debian specific utilities are installed (not Jessie)
  apt:
    pkg: "{{utilities_distribution_no_jessie}}"
  when: ansible_os_family == "Debian" and
        ansible_distribution_release != "jessie"

- name: Utilities | Make sure the list of addtitional tools and utilities are installed
  apt:
    pkg: "{{utilities_extras}}"
  when: utilities_extras|length > 0
