---
- name: Utilities | Select vars file for distribution (first found)
  include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - defaults.yml
      paths:
        - "{{ role_path }}/vars"

- name: Utilities | Build final package list (apply excludes and renames)
  set_fact:
    utilities_packages: "{{ utilities_packages | default([]) + [ (utilities_renames[item] if utilities_renames is defined and (item in utilities_renames) else item) ] }}"
  loop: "{{ utilities_base }}"
  when: utilities_exclude is not defined or item not in utilities_exclude

- name: Utilities | Extend with distribution specific packages (Debian family)
  set_fact:
    utilities_packages: "{{ utilities_packages + (utilities_distribution_debian | default([])) }}"
  when: ansible_facts['os_family'] == 'Debian'

- name: Utilities | Ensure packages are installed (Debian family)
  apt:
    name: "{{ utilities_packages | difference(utilities_distribution_exclude | default([])) }}"
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == 'Debian'

- name: Utilities | Make sure the list of addtitional tools and utilities are installed
  apt:
    pkg: "{{utilities_extras}}"
  when: utilities_extras | length > 0
