# file: utilities/tasks/main.yml

- name: Utilities | Make sure some basic tools are installed
  apt:
    pkg: "{{item}}"
  with_items: utilities_base

- name: Utilities | Make sure the list of addtitional tools are installed
  apt:
    pkg: "{{item}}"
  with_items: utilities_extras
  when: utilities_extras|length > 0
